# Generated by Django 4.1.6 on 2023-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
