# Generated by Django 4.1.7 on 2023-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('frames_data', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.CharField(default='', max_length=1000)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('detected_object_id', models.IntegerField(default=0)),
                ('correct_object_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
