# Generated by Django 4.1.7 on 2023-04-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('objects_data', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_trusted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('meta_data', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
