# Generated by Django 4.1.7 on 2023-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_regions',
            fields=[
                ('version', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='ai_models/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='Mapping_regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('file_location', models.CharField(max_length=100)),
            ],
        ),
    ]
