# Generated by Django 4.1.7 on 2023-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI_regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AI_version', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('coordinates', models.JSONField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('creator_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
