# Generated by Django 4.1.7 on 2023-03-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_regions',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ai_regions',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
