# Generated by Django 4.1.7 on 2023-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_ai_regions_id_alter_ai_regions_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_regions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ai_models/'),
        ),
    ]
